# Connexion à PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=bigboss

# Hibernate crée automatiquement les tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Affiche les requêtes SQL dans le terminal (utile pour apprendre)
spring.jpa.show-sql=true

# Port du serveur
server.port=8080
spring.application.name=portfolio-backend
