spring.datasource.url=jdbc:postgresql://dpg-d90qkvgk1i2s73ftif70-a.frankfurt-postgres.render.com:5432/portfolio_db_aasq
spring.datasource.username=portfolio_db_aasq_user
spring.datasource.password=ffizcLSyTp36UyblSKFqoBYAwbPCbgMy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}